### ISSUE TITLE
pip install goes into weird mode

### ISSUE THREAD

**Issue by raphaeldussin** [jkrasting/cmip_basins#16]
```pip install cmip_basins```

installs 50 versions of each package, with warnings:

```
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
```

you may want to add packages from the ci/requirements to setup.cfg's install_requires and if you have a conda environment that worked use the versions number of the dependencies to thin out the version pip will try to combine.

**Comment by raphaeldussin** [comment]
I think it's cartopy throwing us into a loop, which is probably required by regionmask, maybe remove this one from install_requires ?

**Comment by jkrasting** [comment]
That is odd.  Cartopy is a mess with pip.  I struggled with how to handle this since `regionmask` is critical to this package.  I wish there was a way to disable package dependencies from `requirements.txt` but it looks like you can only do this is from the command line.

**Comment by jkrasting** [comment]
This should be addressed by the newest release.
