### ISSUE TITLE
Possible overlap with cmip6_preprocessing?

### ISSUE THREAD

**Issue by jbusecke** [jkrasting/cmip_basins#2]
Just saw this in my feed and wanted to see if this might have some overlap with [cmip6_preprocessing](https://github.com/jbusecke/cmip6_preprocessing/blob/master/doc/regionmask.ipynb).

**Comment by jkrasting** [comment]
Possibly @jbusecke.  We’re attempting to replace an older flood-filling based approach used to reproduce our existing basin mask definitions.  They are slightly different than the one you show here and they are also different from the standard basin masks provided by World Ocean Atlas.

**Comment by jbusecke** [comment]
Thanks for the clarification @jkrasting.
